* Взаимодействующие сущности

  Сайт - там происходит формирование заказа
  1С-Ravta - сюда заказ попадает с сайта
  1С-Поставщика - одна из 1С поставщиков, у которых Ravta
  перезаказывает товар, заказанный клиентом на сайте.

* Организация хранения номенклатуры

** В 1С-Ravta создать регистр "Номенклатура"

   Каждый товар в номенклатуре имеет уникальный идентификатор, которым
   является поле "КодРавта".

   Для каждой группы товаров (если это возможно - уточнить у 1С-БиТ)
   определяются пользовательские поля, такие как вязкость для масел,
   диаметр для шин и дисков и.т.п.

   Приблизительный формат:

   | КодRavta | НаименованиеRavta | Марка | Фасовка | Вязкость | ... |
   |----------+-------------------+-------+---------+----------+-----|
   |    97781 | Castrol           | EDGE  | 1 литр  | 0W/30    | ... |

   "Номенклатура" загружается только из xls-файлов. Фирма 1C-БиТ
   разрабатывает механизм загрузки номенклатуры в 1C-Ravta из
   xls-файлов.


** В 1С-Ravta создать регистр "Номенклатура поставщиков"

   В нём будет храниться список соответствий товаров у поставщиков и
   товаров в базе 1С в разрезе поставщиков.

   | Поставщик | НаименованиеПоставщика               | КодRavta | Цена | СрокДоставки | Остаток | ... |
   |-----------+--------------------------------------+----------+------+--------------+---------+-----|
   | Кратер    | Масло Castrol EDGE 0W30 (1л)         |   097781 | 1563 | 2д           |       3 |     |
   | Кратер    | Смазка для цепи ГРМ Motul DD4        |   252345 | 1334 | 7д           |       5 |     |
   | Нафтен    | масло моторное Castrol EDGE 0W/30 1л |   097781 | 1232 | 1д           |      78 |     |
   | Тенеф     | Жидкость в бачок омывателя Extra     |   235435 |  342 | 1д           |       5 |     |

   Как можно видеть в этом примере, первый и третий товар идентичны,
   но поставляются разными поставщиками.

   Пара ("КодПоставщика", "НаименованиеПоставщика") однозначно
   идентифицирует товар, заказываемый у поставщика.

   Поле "КодРавта" связывает товар поставщика с товаром Ravta.

   Поле "Остаток" содержит количество свободных остатков на складе поставщика.

   "Номенклатура поставщиков" загружается из xls-файлов и через
   механизм обмена данными между 1С-Ravta и 1C-Поставщиков. Фирма
   1C-БиТ разрабатывает механизм загрузки номенклатуры в 1C-Ravta из
   xls-файлов и механизм обмена данными между 1С-Ravta и
   1C-Поставщиков.

   Эти данные на текущий момент формируются, доступна тестовая
   выборка.


* Организация обмена данными

** Выгрузка остатков товаров от 1С-Поставщика в 1С-Ravta

   1С-БиТ разрабатывает процедуру выгрузки остатков товаров (с ценами)
   по каждом поставщику в файл.

   1С-БиТ разрабатывает процедуру загрузка этого файла в 1С-Ravta в
   регистр "Номенклатура поставщиков"

   Поставщик (Например: "Тенеф")

   | НаименованиеПоставщика        | Остаток | Цена |
   |-------------------------------+---------+------|
   | Масло Castrol EDGE 0W30 (1л)  |    2740 |  232 |
   | Смазка для цепи ГРМ Motul DD4 |    1250 |  345 |


** Организация обмена движений товаров у поставщиков и базы 1С-Ravta

   1C-БиТ разрабатывает процедуру которая вызывается при успешном
   проведении документов движения товаров в базах 1С у поставщиков.

   Эта процедура вызывается из следующих документов:

   - оприходование
   - списание
   - поступление
   - реализация
   - перемещение
   - резервирование
   - снятие резерва
   - изменение цены товара

   Процедура формирует xml файл и сохраняет его в специальном каталоге
   локально. Файл xml будет содержать следующую информацию для
   изменившихся товаров:

   Поставщик: (Например: "Тенеф")

   | НаименованиеПоставщика        | Остаток | Цена | ... |
   |-------------------------------+---------+------+-----|
   | Масло Castrol EDGE 0W30 (1л)  |    2740 |  232 |     |
   | Смазка для цепи ГРМ Motul DD4 |    1250 |  345 |     |

   Этот файл будет сохраняться в специальный каталог обмена на сервере
   1C-Поставщика, после чего будет с определенной периодичностью
   загружаться по сети в 1C-Ravta (и, возможно, на сайт).

   При инициализации системы необходимо выгрузить в этот файл все
   товары поставщика.


* Организация передачи файла обмена с информацией о движении товара на сайт

** Регламентное задание создания xml-файла в каталоге обмена

   1C-БиТ создает и настраивает регламентное задание, которое с заданной
   периодичностью запускает процедуру отправки файлов в каталоги
   обмена.

** Процедура отправки файлов обмена на сайт

   1С-БиТ разрабатывает процедуру отправки файлов xml на сайт из специального
   каталога - процедура опрашивает специальный каталог и последовательно выгружает
   файлы на сайт, по указанном адресу (пример формата адреса:
   http://site.com/uri/to/script)

   При успешной выгрузке файл удаляется из специального каталога -
   прохождение выгрузок можно контролировать визуально, обновляя каталог.

   Альтернативный вариант - используя сетевую файловую систему, подобную NFS или другое
   программное средство мы могли бы расшарить каталог обмена и сделать
   его доступным по сети. Необходимо уточнить наличие файровола,
   проксей и программных средств, которые могут обеспечить это.

   Еще один вариант - внешнее windows-приложение, умеющая смотреть в
   каталог и отправлять файлы по http (возможно через прокси)

   Note: Необходимо интерфейс показывающий состояние выгрузок
   (прошли/не прошли/сбой/попытка) на сайте (для целей тестирования).


* Организация обмена между сайтом и 1С-Ravta

** Получение заказа с сайта

   1С-БиТ разрабатывает процедуру, которая с заданной периодичностью
   опрашивает сайт и получает информацию по сделанным заказам.

   Процедура получает данные в которых содержится информация по
   заказу. На основании их происходит автоматическое формирование
   документа "Заказ покупателя"

   Note: Нужна структура информации по заказу.

   Note: Нужна структура хранения заказов в 1С

   Note: Нужен интерфейс для отправки тестового заказа с сайта.

* Организация обмена между базами 1С поставщиков и сайта

  Это запасной сценарий, отрабатывающийся в случае проблем на стороне
  1С-Ravta или для ускорения прохождения заказа.

  1С-БиТ разрабатывает процедуру, которая с заданной периодичностью
  опрашивает сайт и получает информацию по сделанным заказам.

  Процедура получает данные в которых содержится информация по
  заказу. На основании их происходит автоматическое формирование
  документа "Заказ покупателя". Клиентом в данном сценарии выступает
  организация Ravta.

* Документооборот

  1С-БиТ разрабатывает процедуры создания и печати всех необходимых
  документов связанных с прохождением заказа и доставкой
  (счетов-фактур, накладных и.т.п)
